import "sample/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Topnav from "./page2/topnav";

export const metadata: Metadata = {
  title: "Chiikawa",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/strawberry icon.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="min-h-screen bg-gradient-to-b from-[#F7A5A5] to-[#FFDDE0] text-black">
        <Topnav />
        <main className="pt-14 py-4">{children}</main>
      </body>
    </html>
  );
}
